name: GMAnnotationTool
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cairo=1.18.0
  - dav1d=1.2.1
  - double-conversion=3.3.0
  - expat=2.6.2
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - graphite2=1.3.13
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - icu=73.2
  - imath=3.1.11
  - intel-openmp=2024.1.0
  - jasper=4.2.4
  - khronos-opencl-icd-loader=2023.04.17
  - krb5=1.21.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=18.1.8
  - libcurl=8.8.0
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libglib=2.80.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.10.0
  - libopenvino=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-intel-cpu-plugin=2024.2.0
  - libopenvino-intel-gpu-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - mkl=2024.1.0
  - numpy=2.0.0
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openssl=3.3.1
  - pandas=2.2.2
  - pcre2=10.43
  - pip=24.0
  - pixman=0.43.4
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - py-opencv=4.10.0
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - qt6-main=6.7.2
  - setuptools=70.1.1
  - six=1.16.0
  - snappy=1.2.0
  - svt-av1=2.1.0
  - tbb=2021.12.0
  - tk=8.6.13
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
    - blinker==1.8.2
    - certifi==2024.6.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - dash==2.17.1
    - dash-bootstrap-components==1.6.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - flask==3.0.3
    - idna==3.7
    - importlib-metadata==8.0.0
    - itsdangerous==2.2.0
    - jinja2==3.1.4
    - markupsafe==2.1.5
    - nest-asyncio==1.6.0
    - packaging==24.1
    - plotly==5.22.0
    - requests==2.32.3
    - retrying==1.3.4
    - tenacity==8.4.2
    - typing-extensions==4.12.2
    - urllib3==2.2.2
    - werkzeug==3.0.3
    - zipp==3.19.2
